const express = require("express")
const hbs = require("hbs")
const path=require("path")
const app= express()
const staticFiles = path.join(__dirname, "../frontend/static")
const viewsFiles = path.join(__dirname, "../frontend/views")
const layoutsFiles = path.join(__dirname, "../frontend/layouts")
app.use(express.static(staticFiles))
app.set("view engine", "hbs")
app.set("views", viewsFiles)
hbs.registerPartials(layoutsFiles)
const myRoutes = require("./routes/app.routes")
app.use(myRoutes)

module.exports=app